export const destinations = [
  {
    id: 1,
    name: "Santorini, Greece",
    description: "Iconic white-washed buildings with blue domes overlooking the crystal-clear Aegean Sea.",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?q=80&w=800&auto=format&fit=crop",
    location: "Cyclades Islands",
    rating: 4.9,
    bestTime: "Apr-Oct",
    longDescription:
      "Santorini is one of the Cyclades islands in the Aegean Sea. It was devastated by a volcanic eruption in the 16th century BC, forever shaping its rugged landscape. The whitewashed, cubiform houses of its 2 principal towns, Fira and Oia, cling to cliffs above an underwater caldera (crater). They overlook the sea, small islands to the west and beaches made up of black, red and white lava pebbles.",
    highlights: ["Oia Sunset Views", "Fira Town", "Red Beach", "Ancient Akrotiri", "Caldera Boat Tours"],
    activities: [
      {
        name: "Sunset Catamaran Cruise",
        description: "Sail around the caldera on a luxury catamaran, stopping at hot springs and secluded beaches.",
        price: "€120",
        duration: "5 hours",
      },
      {
        name: "Wine Tasting Tour",
        description: "Visit traditional wineries and taste the unique volcanic wines of Santorini.",
        price: "€85",
        duration: "4 hours",
      },
      {
        name: "Akrotiri Archaeological Site",
        description: "Explore the preserved ancient city buried by volcanic ash in the Minoan eruption.",
        price: "€15",
        duration: "2 hours",
      },
    ],
    accommodation: [
      {
        name: "Luxury Caldera View Suites",
        description: "Exclusive suites with private infinity pools overlooking the caldera.",
        priceRange: "$$$",
      },
      {
        name: "Boutique Hotels in Fira",
        description: "Charming hotels in the heart of the capital with easy access to restaurants and shops.",
        priceRange: "$$",
      },
      {
        name: "Beach Resorts in Kamari",
        description: "Family-friendly resorts along the black sand beaches of Kamari.",
        priceRange: "$$",
      },
    ],
    travelTips: [
      "Book accommodations well in advance, especially for summer months",
      "Rent an ATV to explore the island at your own pace",
      "Visit in shoulder seasons (May or September) for fewer crowds",
      "Bring comfortable shoes for walking on cobblestone streets",
      "Reserve restaurants with caldera views ahead of time",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1555400038-63f5ba517a47?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1504512485720-7d83a16ee930?q=80&w=800&auto=format&fit=crop",
    ],
  },
  {
    id: 2,
    name: "Bali, Indonesia",
    description: "Lush rice terraces, sacred temples, and vibrant cultural experiences in this tropical paradise.",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=800&auto=format&fit=crop",
    location: "Southeast Asia",
    rating: 4.8,
    bestTime: "May-Sep",
    longDescription:
      "Bali is an Indonesian island known for its forested volcanic mountains, iconic rice paddies, beaches and coral reefs. The island is home to religious sites such as cliffside Uluwatu Temple. To the south, the beachside city of Kuta has lively bars, while Seminyak, Sanur and Nusa Dua are popular resort towns. The island is also known for its yoga and meditation retreats.",
    highlights: [
      "Ubud Monkey Forest",
      "Tegallalang Rice Terraces",
      "Uluwatu Temple",
      "Sacred Monkey Forest",
      "Tanah Lot Temple",
    ],
    activities: [
      {
        name: "Balinese Cooking Class",
        description: "Learn to prepare traditional Balinese dishes with local ingredients from the market.",
        price: "$45",
        duration: "4 hours",
      },
      {
        name: "Mount Batur Sunrise Trek",
        description: "Hike up an active volcano for breathtaking sunrise views over Lake Batur.",
        price: "$65",
        duration: "6 hours",
      },
      {
        name: "Ubud Art and Craft Tour",
        description: "Visit traditional villages specializing in wood carving, silver work, and painting.",
        price: "$35",
        duration: "5 hours",
      },
    ],
    accommodation: [
      {
        name: "Luxury Villas in Seminyak",
        description: "Private villas with personal pools and butler service near trendy beaches.",
        priceRange: "$$$",
      },
      {
        name: "Eco Retreats in Ubud",
        description: "Sustainable bamboo lodges and yoga retreats nestled in the jungle.",
        priceRange: "$$",
      },
      {
        name: "Beachfront Resorts in Nusa Dua",
        description: "Family-friendly resorts with pristine beaches and water activities.",
        priceRange: "$$",
      },
    ],
    travelTips: [
      "Respect local customs and dress modestly when visiting temples",
      "Negotiate prices at markets and with taxi drivers",
      "Be cautious of wild monkeys - they can be aggressive",
      "Drink bottled water and avoid ice in remote areas",
      "Learn a few basic Indonesian phrases",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1604999333679-b86d54738315?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1558005530-a7958896ec60?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1555400038-63f5ba517a47?q=80&w=800&auto=format&fit=crop",
    ],
  },
  {
    id: 3,
    name: "Amalfi Coast, Italy",
    description: "Dramatic coastline with colorful villages perched on cliffs above the Mediterranean.",
    image: "https://images.unsplash.com/photo-1612698093158-e07ac200d44e?q=80&w=800&auto=format&fit=crop",
    location: "Southern Italy",
    rating: 4.9,
    bestTime: "May-Sep",
    longDescription:
      "The Amalfi Coast is a 50-kilometer stretch of coastline along the southern edge of Italy's Sorrentine Peninsula. It's a popular holiday destination, with sheer cliffs and a rugged shoreline dotted with small beaches and pastel-colored fishing villages. The coastal road between the port city of Salerno and clifftop Sorrento winds past grand villas, terraced vineyards and cliffside lemon groves.",
    highlights: ["Positano Village", "Ravello Gardens", "Amalfi Cathedral", "Path of the Gods Hike", "Emerald Grotto"],
    activities: [
      {
        name: "Private Boat Tour",
        description: "Cruise along the coast with stops for swimming in hidden coves and grottos.",
        price: "€180",
        duration: "6 hours",
      },
      {
        name: "Limoncello Tasting",
        description: "Visit a traditional lemon grove and learn how the famous liqueur is made.",
        price: "€40",
        duration: "2 hours",
      },
      {
        name: "Cooking Class in Ravello",
        description: "Learn to make pasta and other Italian specialties with panoramic views.",
        price: "€95",
        duration: "4 hours",
      },
    ],
    accommodation: [
      {
        name: "Cliffside Luxury Hotels",
        description: "Exclusive accommodations carved into the cliffs with infinity pools.",
        priceRange: "$$$",
      },
      {
        name: "Historic Villas",
        description: "Restored noble residences with gardens and Mediterranean views.",
        priceRange: "$$$",
      },
      {
        name: "Boutique B&Bs",
        description: "Family-run establishments with authentic Italian hospitality.",
        priceRange: "$$",
      },
    ],
    travelTips: [
      "Book accommodations months in advance for summer visits",
      "Be prepared for lots of stairs in the vertical villages",
      "Consider visiting in May or September to avoid peak crowds",
      "Take motion sickness medication if you're sensitive to winding roads",
      "Use public ferries to travel between towns and avoid traffic",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1533676802871-eca1ae998cd5?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1633321088355-d0f21691dd09?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?q=80&w=800&auto=format&fit=crop",
    ],
  },
  {
    id: 4,
    name: "Kyoto, Japan",
    description: "Ancient temples, traditional gardens and the beautiful cherry blossoms in spring.",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop",
    location: "Kansai Region",
    rating: 4.7,
    bestTime: "Mar-May",
    longDescription:
      "Kyoto, once the capital of Japan, is a city on the island of Honshu. It's famous for its numerous classical Buddhist temples, as well as gardens, imperial palaces, Shinto shrines and traditional wooden houses. It's also known for formal traditions such as kaiseki dining, consisting of multiple courses of precise dishes, and geisha, female entertainers often found in the Gion district.",
    highlights: [
      "Fushimi Inari Shrine",
      "Arashiyama Bamboo Grove",
      "Kinkaku-ji (Golden Pavilion)",
      "Gion District",
      "Kiyomizu-dera Temple",
    ],
    activities: [
      {
        name: "Tea Ceremony Experience",
        description: "Participate in a traditional Japanese tea ceremony in an authentic setting.",
        price: "¥5,000",
        duration: "1.5 hours",
      },
      {
        name: "Kimono Rental and Photoshoot",
        description: "Dress in a traditional kimono and explore historic districts for memorable photos.",
        price: "¥6,000",
        duration: "4 hours",
      },
      {
        name: "Sake Tasting Tour",
        description: "Visit local breweries and learn about the production of Japan's famous rice wine.",
        price: "¥8,000",
        duration: "3 hours",
      },
    ],
    accommodation: [
      {
        name: "Traditional Ryokans",
        description: "Experience authentic Japanese inns with tatami floors and futon bedding.",
        priceRange: "$$$",
      },
      {
        name: "Machiya Townhouses",
        description: "Restored traditional wooden townhouses offering privacy and cultural immersion.",
        priceRange: "$$",
      },
      {
        name: "Modern Hotels in Central Kyoto",
        description: "Contemporary accommodations with easy access to transportation and attractions.",
        priceRange: "$$",
      },
    ],
    travelTips: [
      "Purchase a bus pass for unlimited travel around the city",
      "Visit popular temples early in the morning to avoid crowds",
      "Book accommodations well in advance for cherry blossom season",
      "Respect quiet zones and photography rules at temples",
      "Learn basic Japanese phrases for a more enriching experience",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1528360983277-13d401cdc186?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1493780474015-ba834fd0ce2f?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1558862107-d49ef2a04d72?q=80&w=800&auto=format&fit=crop",
    ],
  },
  {
    id: 5,
    name: "Maldives",
    description: "Turquoise lagoons, overwater bungalows, and pristine white sand beaches in this island paradise.",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=800&auto=format&fit=crop",
    location: "Indian Ocean",
    rating: 4.9,
    bestTime: "Nov-Apr",
    longDescription:
      "The Maldives is a tropical nation in the Indian Ocean composed of 26 ring-shaped atolls, which are made up of more than 1,000 coral islands. It's known for its beaches, blue lagoons and extensive reefs. The capital, Malé, has a busy fish market, restaurants and shops on the main road, Majeedhee Magu, and 17th-century Hukuru Miskiy (also known as Friday Mosque) made of carved white coral.",
    highlights: [
      "Overwater Bungalows",
      "Underwater Restaurants",
      "Bioluminescent Beaches",
      "Manta Ray Sanctuaries",
      "House Reef Snorkeling",
    ],
    activities: [
      {
        name: "Scuba Diving Excursion",
        description: "Explore vibrant coral reefs and encounter diverse marine life including sharks and rays.",
        price: "$120",
        duration: "3 hours",
      },
      {
        name: "Sunset Dolphin Cruise",
        description: "Sail into the sunset while watching playful dolphins in their natural habitat.",
        price: "$85",
        duration: "2 hours",
      },
      {
        name: "Island Hopping Tour",
        description: "Visit multiple islands and experience different aspects of Maldivian culture.",
        price: "$150",
        duration: "Full day",
      },
    ],
    accommodation: [
      {
        name: "Luxury Overwater Villas",
        description: "Exclusive accommodations built directly over the lagoon with glass floors and private pools.",
        priceRange: "$$$",
      },
      {
        name: "Beach Bungalows",
        description: "Beachfront accommodations with direct access to white sand beaches.",
        priceRange: "$$$",
      },
      {
        name: "Guesthouses on Local Islands",
        description: "More affordable options on inhabited islands offering cultural experiences.",
        priceRange: "$$",
      },
    ],
    travelTips: [
      "Respect local customs and dress modestly when visiting inhabited islands",
      "Bring plenty of sunscreen - the equatorial sun is intense",
      "Pack reef-safe sunscreen to protect the coral ecosystems",
      "Be aware that alcohol is only available at resort islands",
      "Consider a seaplane transfer for spectacular aerial views",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1540202404-a2f29016b523?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544550581-1bcabf842b77?q=80&w=800&auto=format&fit=crop",
    ],
  },
  {
    id: 6,
    name: "Swiss Alps",
    description: "Breathtaking mountain scenery, charming villages, and world-class skiing opportunities.",
    image: "https://images.unsplash.com/photo-1531210483974-4f8c1f33fd35?q=80&w=800&auto=format&fit=crop",
    location: "Switzerland",
    rating: 4.8,
    bestTime: "Dec-Mar",
    longDescription:
      "The Swiss Alps are the portion of the Alps mountain range that lies within Switzerland. Because of their central position within the entire Alpine range, they are also known as the Central Alps. The highest summit in the Swiss Alps is Monte Rosa (4,634 m) near the Swiss-Italian border. The region is famous for its dramatic peaks, pristine lakes, and world-class ski resorts.",
    highlights: ["Matterhorn Peak", "Jungfraujoch - Top of Europe", "Lake Geneva", "Interlaken", "Zermatt Village"],
    activities: [
      {
        name: "Glacier Express Train Journey",
        description: "Travel on the world's most scenic train route through mountains and valleys.",
        price: "CHF 150",
        duration: "8 hours",
      },
      {
        name: "Ski or Snowboard Day Pass",
        description: "Access world-class slopes in resorts like Zermatt, Verbier, or St. Moritz.",
        price: "CHF 85",
        duration: "Full day",
      },
      {
        name: "Paragliding Experience",
        description: "Soar over Alpine landscapes with a tandem paragliding flight.",
        price: "CHF 180",
        duration: "1 hour",
      },
    ],
    accommodation: [
      {
        name: "Luxury Mountain Chalets",
        description: "Private wooden chalets with fireplaces, hot tubs, and mountain views.",
        priceRange: "$$$",
      },
      {
        name: "Historic Alpine Hotels",
        description: "Grand hotels with Belle Époque charm and modern amenities.",
        priceRange: "$$$",
      },
      {
        name: "Mountain Lodges",
        description: "Cozy accommodations with easy access to hiking trails and ski slopes.",
        priceRange: "$$",
      },
    ],
    travelTips: [
      "Purchase a Swiss Travel Pass for unlimited public transportation",
      "Book accommodations well in advance for winter ski season",
      "Pack layers - mountain weather can change rapidly",
      "Learn basic German, French, or Italian phrases depending on the region",
      "Carry cash as some mountain establishments don't accept cards",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1527668752968-14dc70a27c95?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1508437029947-6fe2a1b77ddf?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=800&auto=format&fit=crop",
    ],
  },
  {
    id: 7,
    name: "Machu Picchu, Peru",
    description: "The ancient Incan citadel set high in the Andes Mountains, shrouded in mystery.",
    image: "https://images.unsplash.com/photo-1526392060635-9d6019884377?q=80&w=800&auto=format&fit=crop",
    location: "Cusco Region",
    rating: 4.9,
    bestTime: "May-Oct",
    longDescription:
      "Machu Picchu is an Incan citadel set high in the Andes Mountains in Peru, above the Urubamba River valley. Built in the 15th century and later abandoned, it's renowned for its sophisticated dry-stone walls that fuse huge blocks without the use of mortar, intriguing buildings that play on astronomical alignments and panoramic views. Its exact former use remains a mystery.",
    highlights: [
      "Sun Gate (Inti Punku)",
      "Huayna Picchu Mountain",
      "Temple of the Sun",
      "Intihuatana Stone",
      "Sacred Valley",
    ],
    activities: [
      {
        name: "Inca Trail Trek",
        description: "Multi-day hiking adventure along ancient pathways to Machu Picchu.",
        price: "$650",
        duration: "4 days",
      },
      {
        name: "Guided Tour of Machu Picchu",
        description: "Expert-led exploration of the archaeological site with historical context.",
        price: "$85",
        duration: "2.5 hours",
      },
      {
        name: "Sacred Valley Tour",
        description: "Visit Incan ruins, traditional markets, and stunning landscapes in the valley.",
        price: "$120",
        duration: "Full day",
      },
    ],
    accommodation: [
      {
        name: "Luxury Hotels in Aguas Calientes",
        description: "Upscale accommodations at the foot of Machu Picchu with mountain views.",
        priceRange: "$$$",
      },
      {
        name: "Historic Hotels in Cusco",
        description: "Colonial-era buildings converted into comfortable hotels in the ancient Incan capital.",
        priceRange: "$$",
      },
      {
        name: "Eco-Lodges in Sacred Valley",
        description: "Sustainable accommodations nestled in the stunning valley between Cusco and Machu Picchu.",
        priceRange: "$$",
      },
    ],
    travelTips: [
      "Book Machu Picchu tickets months in advance - they sell out quickly",
      "Spend a few days in Cusco to acclimatize to the altitude",
      "Bring sun protection, rain gear, and layers for changing mountain weather",
      "Consider hiring a guide to fully appreciate the historical significance",
      "Take the early morning train to beat the crowds",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1587595431973-160d0d94add1?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1548791693-0a9ece4d7c1c?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1531065208531-4036c0dba3d3?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1553374402-559e8b431161?q=80&w=800&auto=format&fit=crop",
    ],
  },
  {
    id: 8,
    name: "Great Barrier Reef",
    description: "The world's largest coral reef system with vibrant marine life and stunning underwater scenery.",
    image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?q=80&w=800&auto=format&fit=crop",
    location: "Australia",
    rating: 4.8,
    bestTime: "Jun-Oct",
    longDescription:
      "The Great Barrier Reef is the world's largest coral reef system composed of over 2,900 individual reefs and 900 islands stretching for over 2,300 kilometers over an area of approximately 344,400 square kilometers. The reef is located in the Coral Sea, off the coast of Queensland, Australia. The Great Barrier Reef can be seen from outer space and is the world's biggest single structure made by living organisms.",
    highlights: [
      "Heart Reef",
      "Whitehaven Beach",
      "Outer Reef Diving Sites",
      "Hamilton Island",
      "Underwater Observatories",
    ],
    activities: [
      {
        name: "Snorkeling Tour",
        description: "Explore vibrant coral gardens and encounter tropical fish in shallow waters.",
        price: "AUD 150",
        duration: "Half day",
      },
      {
        name: "Scuba Diving Expedition",
        description: "Dive into the depths to see coral formations, sharks, rays, and turtles.",
        price: "AUD 250",
        duration: "Full day",
      },
      {
        name: "Scenic Helicopter Flight",
        description: "Aerial tour offering spectacular views of the reef, including the famous Heart Reef.",
        price: "AUD 300",
        duration: "30 minutes",
      },
    ],
    accommodation: [
      {
        name: "Island Resorts",
        description: "Exclusive accommodations on private islands within the Great Barrier Reef Marine Park.",
        priceRange: "$$$",
      },
      {
        name: "Beachfront Hotels in Cairns",
        description: "Comfortable accommodations in the main gateway city to the reef.",
        priceRange: "$$",
      },
      {
        name: "Eco-Resorts in Port Douglas",
        description: "Sustainable luxury in a more relaxed setting north of Cairns.",
        priceRange: "$$$",
      },
    ],
    travelTips: [
      "Visit during the Australian winter (June-August) for the best visibility",
      "Book reef tours in advance during peak season",
      "Wear reef-safe sunscreen to protect the coral ecosystem",
      "Consider a stinger suit during jellyfish season (November-May)",
      "Choose eco-certified tour operators committed to reef conservation",
    ],
    gallery: [
      "https://images.unsplash.com/photo-1560750588-73207b1ef5b8?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1570789210967-2cac24afeb00?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1582153465561-a2d8f8a5e2f7?q=80&w=800&auto=format&fit=crop",
    ],
  },
]
